//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MsgBaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MsgBase), typeof(System.Object));
		L.RegFunction("GetMsgManager", GetMsgManager);
		L.RegFunction("GetState", GetState);
		L.RegFunction("ChangeMsgId", ChangeMsgId);
		L.RegFunction("New", _CreateMsgBase);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("MsgId", get_MsgId, set_MsgId);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMsgBase(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				MsgBase obj = new MsgBase();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1)
			{
				ushort arg0 = (ushort)LuaDLL.luaL_checknumber(L, 1);
				MsgBase obj = new MsgBase(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MsgBase.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMsgManager(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MsgBase obj = (MsgBase)ToLua.CheckObject<MsgBase>(L, 1);
			MsgManager o = obj.GetMsgManager();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetState(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MsgBase obj = (MsgBase)ToLua.CheckObject<MsgBase>(L, 1);
			byte o = obj.GetState();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ChangeMsgId(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MsgBase obj = (MsgBase)ToLua.CheckObject<MsgBase>(L, 1);
			ushort arg0 = (ushort)LuaDLL.luaL_checknumber(L, 2);
			obj.ChangeMsgId(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MsgId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MsgBase obj = (MsgBase)o;
			ushort ret = obj.MsgId;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MsgId on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MsgId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MsgBase obj = (MsgBase)o;
			ushort arg0 = (ushort)LuaDLL.luaL_checknumber(L, 2);
			obj.MsgId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MsgId on a nil value");
		}
	}
}

